---
name: Catalyst-Model-ISBNDB
version: 0.20
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: Catalyst model for accessing the isbndb.com REST interface
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  WebService::ISBNDB: 0.31
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Catalyst::Helper::Model::ISBNDB:
    file: lib/Catalyst/Helper/Model/ISBNDB.pm
    version: 0.10
  Catalyst::Model::ISBNDB:
    file: lib/Catalyst/Model/ISBNDB.pm
    version: 0.10
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
